<?php echo $this->doctype() . "\n" ?>
<html>
    <head>
        <?php echo $this->headMeta() . "\n" ?>
        <?php echo $this->headTitle('Monster Objective'); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>

    </head>
    <body>
        <div class="navbar">
            <div class="navbar-inner">
                <a class="brand" href="<?php echo $this->baseurl; ?>"><strong>Monster<sup>&copy;</sup> Objective</strong></a>
                <div class="iconoBarraSuperior">
                    <img src="<?php echo $this->baseurl; ?>/bootstrap/img/logo.png" alt="monster" width="25">
                </div>
            </div>
        </div>
        
        <!-- Contenido pagina principal -->
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span8"> 
                    <h1 id="bienvenida"> Bienvenidos a Monster<sup>&reg</sup>Objective </h1>
                    <h4 class="bienvenida2">Márcate un reto.</h4> 
                    <h4 class="bienvenida2">Establece tus propios límites...¿serás capaz?</h4>
                </div>
                <div class="span4">
                    <div class="principal"> 
                        <img src="<?php echo $this->baseurl; ?>/bootstrap/img/logo.png" alt="monster" width="90"> 
                        <a href="<?php echo $this->baseurl; ?>/retos/index/index"><button style="margin-left:15px;" class="btn btn-info">Acceder a Objective<sup>&reg</sup></button></a>
                    </div>
                </div>
            </div>
        </div>  
        <div class="pie">
            <small><sup>&copy</sup>2013 MONSTER ENERGY COMPANY. TODOS LOS DERECHOS RESERVADOS. | Diseño Web by Troll</small>
        </div>
    </body>
</html>